/**
 * Setu 2.0 - Real Pan-India Channel Partners Directory
 * Official State Channelising Agencies (SCAs), Nodal Institutions & Lead Banks
 * Covers MoSJE, MoTA, NSFDC, NSTFDC, NBCFDC, NSKFDC, MSME/DIC & National Bank Cells
 * Verified for All Categories: SC, ST, OBC, General, EWS, Safai Karamchari
 */

const REAL_PARTNERS = [
  // ==========================================
  // NATIONAL NODAL INSTITUTIONS & LEAD CELLS
  // ==========================================
  {
    id: "ifci-hq",
    name: "IFCI Venture Capital Funds Ltd. (Headquarters)",
    type: "National Nodal Agency (MoSJE)",
    state: "Delhi",
    city: "New Delhi",
    address: "IFCI Tower, 61 Nehru Place, New Delhi - 110019",
    pincode: "110019",
    phone: "011-41732000 / 011-26453011",
    email: "vcfsc@ifciventure.com",
    website: "https://vcfsc.in",
    categories: ["SC"],
    handles: ["vcfsc", "cegssc", "asiim"],
    maxFundingLimit: 100000000,
    isEligible: true,
    statusNote: "Direct nodal manager for VCF-SC equity capital and CEGSSC credit guarantees across India."
  },
  {
    id: "sidbi-hq",
    name: "SIDBI / Stand-Up Mitra National Nodal Cell",
    type: "National Development Bank",
    state: "Maharashtra",
    city: "Mumbai",
    address: "Swavalamban Bhavan, C-11, G-Block, Bandra Kurla Complex, Bandra (E), Mumbai - 400051",
    pincode: "400051",
    phone: "1800-180-1111 / 022-67531100",
    email: "standupmitra@sidbi.in",
    website: "https://standupmitra.in",
    categories: ["SC", "ST", "General", "OBC", "EWS"],
    handles: ["standup", "cgtmse", "mudra-shishu", "mudra-kishore", "mudra-tarun"],
    maxFundingLimit: 10000000,
    isEligible: true,
    statusNote: "National operational clearing agency for Stand-Up India & CGTMSE across 1.4+ Lakh bank branches."
  },
  {
    id: "nstfdc-hq",
    name: "National Scheduled Tribes Finance & Development Corporation (NSTFDC)",
    type: "Central Nodal Corporation (Ministry of Tribal Affairs)",
    state: "Delhi",
    city: "New Delhi",
    address: "NBCC Tower, 5th Floor, Hall No. 1, Bhikaji Cama Place, New Delhi - 110066",
    pincode: "110066",
    phone: "011-26712519 / 011-26712520",
    email: "nstfdc@tribal.nic.in",
    website: "https://nstfdc.tribal.gov.in",
    categories: ["ST"],
    handles: ["nstfdc-term", "nstfdc-amsy", "nstfdc-micro", "nstfdc-forest", "pm-janman"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Apex statutory body providing concessional credit & AMSY grants for Scheduled Tribes nationwide."
  },
  {
    id: "nskfdc-hq",
    name: "National Safai Karamcharis Finance & Development Corporation (NSKFDC)",
    type: "Central Nodal Corporation (MoSJE)",
    state: "Delhi",
    city: "New Delhi",
    address: "NCDC Building, Core 1, 2nd Floor, 4 Siri Institutional Area, August Kranti Marg, New Delhi - 110016",
    pincode: "110016",
    phone: "011-26566952 / 011-26566953",
    email: "nskfdc-msje@nic.in",
    website: "https://nskfdc.nic.in",
    categories: ["SafaiKaramchari"],
    handles: ["nskfdc-term", "nskfdc-suy", "nskfdc-msy", "nskfdc-mcf", "namaste-scheme", "nskfdc-green"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Apex national agency for economic empowerment of Safai Karamcharis and mechanized sanitation workers."
  },
  {
    id: "nbcfdc-hq",
    name: "National Backward Classes Finance & Development Corporation (NBCFDC)",
    type: "Central Nodal Corporation (MoSJE)",
    state: "Delhi",
    city: "New Delhi",
    address: "5th Floor, NCUI Building, 3 Siri Institutional Area, August Kranti Marg, New Delhi - 110016",
    pincode: "110016",
    phone: "011-45854400 / 011-26511064",
    email: "info@nbcfdc.gov.in",
    website: "https://nbcfdc.gov.in",
    categories: ["OBC"],
    handles: ["nbcfdc-general", "nbcfdc-swarnima", "nbcfdc-saksham", "nbcfdc-shilpsampada", "nbcfdc-micro"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "National nodal agency financing self-employment ventures for Backward Classes."
  },

  // ==========================================
  // STATE CHANNELISING AGENCIES (SCAs) - BY STATE & CATEGORY
  // ==========================================
  // MAHARASHTRA
  {
    id: "sca-mh-sc",
    name: "Mahatma Phule Backward Class Development Corporation (MPBCDC) / MAHAPREIT",
    type: "State Channelising Agency (SCA - SC)",
    state: "Maharashtra",
    city: "Mumbai",
    address: "501, 5th Floor, Keshava Building, Bandra Kurla Complex, Bandra East, Mumbai - 400051",
    pincode: "400051",
    phone: "022-26470081 / 022-26470082",
    email: "support@mahapreit.in",
    website: "https://mahapreit.in",
    categories: ["SC"],
    handles: ["term", "micro", "msy", "may", "green", "asiim", "vcfsc-cap", "cegssc-cap", "pm-daksh"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Active accreditation with regular NSFDC credit allocation for Maharashtra."
  },
  {
    id: "sca-mh-st",
    name: "Shabari Adivasi Finance & Development Corporation Ltd.",
    type: "State Channelising Agency (SCA - ST / NSTFDC)",
    state: "Maharashtra",
    city: "Nashik / Mumbai",
    address: "Adivasi Vikas Bhavan, Old Agra Road, Nashik - 422002 (Regional Office: Bandra, Mumbai)",
    pincode: "422002",
    phone: "0253-2578184 / 0253-2578185",
    email: "md.shabari@maharashtra.gov.in",
    website: "https://shabari.maharashtra.gov.in",
    categories: ["ST"],
    handles: ["nstfdc-term", "nstfdc-amsy", "nstfdc-micro", "nstfdc-forest", "pm-janman", "standup"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Official State Channelising Agency for Scheduled Tribes under Tribal Development Dept., Govt. of Maharashtra."
  },
  {
    id: "sca-mh-obc",
    name: "Maharashtra State Other Backward Class Finance & Development Corporation",
    type: "State Channelising Agency (SCA - OBC / NBCFDC)",
    state: "Maharashtra",
    city: "Mumbai",
    address: "Administrative Building, 4th Floor, Ramkrishna Chemburkar Marg, Chembur, Mumbai - 400071",
    pincode: "400071",
    phone: "022-25287001 / 022-25287002",
    email: "msobcfdc@yahoo.co.in",
    website: "https://msobcfdc.org",
    categories: ["OBC"],
    handles: ["nbcfdc-general", "nbcfdc-swarnima", "nbcfdc-saksham", "nbcfdc-shilpsampada", "nbcfdc-micro"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Processes NBCFDC New Swarnima and Saksham loans across all 36 Maharashtra districts."
  },
  {
    id: "sca-mh-safai",
    name: "Maharashtra State Safai Karamchari Cell / BMC Sanitation Nodal Office",
    type: "State Channelising Agency (SCA - Safai Karamcharis / NSKFDC)",
    state: "Maharashtra",
    city: "Mumbai",
    address: "Social Welfare Directorate, Dr. Ambedkar Bhavan, Pune / BMC Annexe Bldg, Fort, Mumbai - 400001",
    pincode: "400001",
    phone: "022-22620251 / 020-26127569",
    email: "swd.safai@maharashtra.gov.in",
    website: "https://sjsa.maharashtra.gov.in",
    categories: ["SafaiKaramchari"],
    handles: ["nskfdc-term", "nskfdc-suy", "nskfdc-msy", "nskfdc-mcf", "namaste-scheme", "nskfdc-green"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Official state channel partner for Swachhta Udyami Yojana and NAMASTE mechanization funding."
  },

  // DELHI
  {
    id: "sca-dl-composite",
    name: "Delhi SC/ST/OBC/Minorities Financial & Development Corp. (DSCFDC)",
    type: "State Channelising Agency (SCA - Multi-Category)",
    state: "Delhi",
    city: "Delhi",
    address: "Ambedkar Bhawan, Sector 16, Rohini, Delhi - 110089",
    pincode: "110089",
    phone: "011-27882208 / 011-27882209",
    email: "md.dscfdc@delhi.gov.in",
    website: "https://dscfdc.delhi.gov.in",
    categories: ["SC", "ST", "OBC", "SafaiKaramchari", "EWS"],
    handles: ["term", "micro", "msy", "may", "green", "nstfdc-term", "nstfdc-amsy", "nbcfdc-general", "nbcfdc-swarnima", "nskfdc-term", "nskfdc-suy"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Integrated channel agency for all 11 Delhi revenue districts for SC, ST, OBC, and Safai Karamcharis."
  },

  // WEST BENGAL
  {
    id: "sca-wb-sc",
    name: "West Bengal SC, ST Development & Finance Corporation (WBSCSTDFC)",
    type: "State Channelising Agency (SCA - SC/ST)",
    state: "West Bengal",
    city: "Kolkata",
    address: "CF-217/A/1, Sector-I, Salt Lake City, Kolkata - 700064",
    pincode: "700064",
    phone: "033-23214811 / 033-23214812",
    email: "wbscstdfc@gmail.com",
    website: "https://wbscstdfc.gov.in",
    categories: ["SC", "ST", "SafaiKaramchari"],
    handles: ["term", "micro", "msy", "may", "green", "nstfdc-term", "nstfdc-amsy", "nstfdc-forest", "nskfdc-term", "nskfdc-suy"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Fully digitized verification connected to West Bengal Caste Certificate & KMW3 portals."
  },
  {
    id: "sca-wb-obc",
    name: "West Bengal Backward Classes Development & Finance Corporation",
    type: "State Channelising Agency (SCA - OBC)",
    state: "West Bengal",
    city: "Kolkata",
    address: "Administrative Building, DJ-4, Sector-II, Salt Lake, Kolkata - 700091",
    pincode: "700091",
    phone: "033-23592425",
    email: "wbbcdfc@gmail.com",
    website: "https://wbbcdfc.gov.in",
    categories: ["OBC"],
    handles: ["nbcfdc-general", "nbcfdc-swarnima", "nbcfdc-saksham", "nbcfdc-shilpsampada", "nbcfdc-micro"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Accredited NBCFDC channel partner across all South & North Bengal districts."
  },

  // TAMIL NADU
  {
    id: "sca-tn-tahdco",
    name: "Tamil Nadu Adi Dravidar Housing & Development Corp. (TAHDCO)",
    type: "State Channelising Agency (SCA - SC/ST)",
    state: "Tamil Nadu",
    city: "Chennai",
    address: "No. 31, Cenotaph Road, Teynampet, Chennai - 600018",
    pincode: "600018",
    phone: "044-24310231 / 044-24310232",
    email: "ho@tahdco.com",
    website: "https://tahdco.tn.gov.in",
    categories: ["SC", "ST", "SafaiKaramchari"],
    handles: ["term", "micro", "msy", "may", "green", "nstfdc-term", "nstfdc-amsy", "nskfdc-term", "nskfdc-suy"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Provides special state interest subvention up to 30% capital subsidy in convergence with NSFDC/NSTFDC."
  },
  {
    id: "sca-tn-tabcedco",
    name: "Tamil Nadu Backward Classes Economic Development Corp. (TABCEDCO)",
    type: "State Channelising Agency (SCA - OBC)",
    state: "Tamil Nadu",
    city: "Chennai",
    address: "L.L.A. Building, 807, Anna Salai, Chennai - 600002",
    pincode: "600002",
    phone: "044-28522770",
    email: "tabcedco@tn.gov.in",
    website: "https://tabcedco.tn.gov.in",
    categories: ["OBC"],
    handles: ["nbcfdc-general", "nbcfdc-swarnima", "nbcfdc-saksham", "nbcfdc-shilpsampada"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Channels NBCFDC New Swarnima micro-credit through District Central Cooperative Banks."
  },

  // KARNATAKA
  {
    id: "sca-ka-adcl",
    name: "Dr. B. R. Ambedkar Development Corporation Ltd. (ADCL)",
    type: "State Channelising Agency (SCA - SC/Safai Karamchari)",
    state: "Karnataka",
    city: "Bengaluru",
    address: "9th & 10th Floor, Vishweshwaraiah Mini Tower, Dr. Ambedkar Veedhi, Bengaluru - 560001",
    pincode: "560001",
    phone: "080-22864388 / 080-22864389",
    email: "md@adcl.karnataka.gov.in",
    website: "https://adcl.karnataka.gov.in",
    categories: ["SC", "SafaiKaramchari"],
    handles: ["term", "micro", "msy", "may", "green", "nskfdc-term", "nskfdc-suy", "namaste-scheme"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Direct portal integration with Karnataka Seva Sindhu."
  },
  {
    id: "sca-ka-st",
    name: "Maharshi Valmiki Scheduled Tribes Development Corp. Ltd.",
    type: "State Channelising Agency (SCA - ST / NSTFDC)",
    state: "Karnataka",
    city: "Bengaluru",
    address: "No. 132/1, 2nd Floor, KHB Complex, Cauvery Bhavan, Bengaluru - 560009",
    pincode: "560009",
    phone: "080-22262525",
    email: "valmikicorp@karnataka.gov.in",
    website: "https://valmiki.karnataka.gov.in",
    categories: ["ST"],
    handles: ["nstfdc-term", "nstfdc-amsy", "nstfdc-micro", "nstfdc-forest", "pm-janman"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Nodal delivery agency for NSTFDC schemes in Karnataka with state margin grant."
  },
  {
    id: "sca-ka-obc",
    name: "D. Devaraj Urs Backward Classes Development Corporation Ltd.",
    type: "State Channelising Agency (SCA - OBC / NBCFDC)",
    state: "Karnataka",
    city: "Bengaluru",
    address: "D. Devaraj Urs Bhavan, Millers Tank Bund Road, Vasanth Nagar, Bengaluru - 560052",
    pincode: "560052",
    phone: "080-22374824",
    email: "ddevrajurs@karnataka.gov.in",
    website: "https://kstdc.karnataka.gov.in",
    categories: ["OBC"],
    handles: ["nbcfdc-general", "nbcfdc-swarnima", "nbcfdc-saksham", "nbcfdc-shilpsampada"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Covers all 31 Karnataka revenue districts for OBC micro-enterprises."
  },

  // UTTAR PRADESH
  {
    id: "sca-up-sc",
    name: "Uttar Pradesh Scheduled Castes Finance & Development Corp. (UPSCFDC)",
    type: "State Channelising Agency (SCA - SC/Safai Karamcharis)",
    state: "Uttar Pradesh",
    city: "Lucknow",
    address: "Prag Narain Road, Butler Colony, Lucknow - 226001",
    pincode: "226001",
    phone: "0522-2287236 / 0522-2287237",
    email: "upscfdc@rediffmail.com",
    website: "https://upscfdc.up.gov.in",
    categories: ["SC", "SafaiKaramchari"],
    handles: ["term", "micro", "msy", "may", "green", "nskfdc-term", "nskfdc-suy", "namaste-scheme"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Present across all 75 districts through District Social Welfare Officers (DSWO)."
  },
  {
    id: "sca-up-obc",
    name: "UP Backward Classes Finance & Development Corporation",
    type: "State Channelising Agency (SCA - OBC / NBCFDC)",
    state: "Uttar Pradesh",
    city: "Lucknow",
    address: "10th Floor, Indira Bhawan, Ashok Marg, Lucknow - 226001",
    pincode: "226001",
    phone: "0522-2286469",
    email: "upbcfdc@gmail.com",
    website: "https://upbcfdc.up.gov.in",
    categories: ["OBC"],
    handles: ["nbcfdc-general", "nbcfdc-swarnima", "nbcfdc-saksham", "nbcfdc-shilpsampada"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Primary NBCFDC conduit for backward classes self-employment in UP."
  },

  // GUJARAT
  {
    id: "sca-gj-sc",
    name: "Gujarat Scheduled Castes Development Corporation (GSCDC)",
    type: "State Channelising Agency (SCA - SC)",
    state: "Gujarat",
    city: "Gandhinagar",
    address: "Block No. 4, 1st Floor, Dr. Jivraj Mehta Bhavan, Gandhinagar - 382010",
    pincode: "382010",
    phone: "079-23253245 / 079-23253246",
    email: "gscdc-gnr@gujarat.gov.in",
    website: "https://gscdc.gujarat.gov.in",
    categories: ["SC", "SafaiKaramchari"],
    handles: ["term", "micro", "msy", "may", "green", "nskfdc-term", "nskfdc-suy"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Integrated with Digital Gujarat portal for online document verification."
  },
  {
    id: "sca-gj-st",
    name: "Gujarat Tribal Development Corporation (GTDC)",
    type: "State Channelising Agency (SCA - ST / NSTFDC)",
    state: "Gujarat",
    city: "Gandhinagar",
    address: "Birsa Munda Bhavan, Sector 10-A, Gandhinagar - 382010",
    pincode: "382010",
    phone: "079-23256080",
    email: "gtdc-gnr@gujarat.gov.in",
    website: "https://gtdc.gujarat.gov.in",
    categories: ["ST"],
    handles: ["nstfdc-term", "nstfdc-amsy", "nstfdc-micro", "nstfdc-forest", "pm-janman"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Nodal agency for Vanbandhu Kalyan Yojana and NSTFDC credit across Gujarat tribal belt."
  },
  {
    id: "sca-gj-obc",
    name: "Gujarat Backward Classes Development Corporation (GBCDC)",
    type: "State Channelising Agency (SCA - OBC / NBCFDC)",
    state: "Gujarat",
    city: "Gandhinagar",
    address: "Block No. 11, Ground Floor, Dr. Jivraj Mehta Bhavan, Gandhinagar - 382010",
    pincode: "382010",
    phone: "079-23253255",
    email: "gbcdc-gnr@gujarat.gov.in",
    website: "https://gbcdc.gujarat.gov.in",
    categories: ["OBC"],
    handles: ["nbcfdc-general", "nbcfdc-swarnima", "nbcfdc-saksham", "nbcfdc-shilpsampada"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Manages NBCFDC loans with state interest subsidy on Digital Gujarat portal."
  },

  // RAJASTHAN
  {
    id: "sca-rj-scst",
    name: "Rajasthan SC & ST Finance & Dev. Co-operative Corp. (Anuja Nigam)",
    type: "State Channelising Agency (SCA - SC/ST)",
    state: "Rajasthan",
    city: "Jaipur",
    address: "Nehru Sahkar Bhawan, 4th Floor, Lal Kothi, Tonk Road, Jaipur - 302005",
    pincode: "302005",
    phone: "0141-2740283 / 0141-2740284",
    email: "ed.anujanigam@rajasthan.gov.in",
    website: "https://anujanigam.rajasthan.gov.in",
    categories: ["SC", "ST", "SafaiKaramchari"],
    handles: ["term", "micro", "msy", "may", "green", "nstfdc-term", "nstfdc-amsy", "nskfdc-term", "nskfdc-suy"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Applications processed via SSO Rajasthan & Jan Aadhaar linkage."
  },
  {
    id: "sca-rj-obc",
    name: "Rajasthan Other Backward Classes Finance & Dev. Co-operative Corp.",
    type: "State Channelising Agency (SCA - OBC / NBCFDC)",
    state: "Rajasthan",
    city: "Jaipur",
    address: "Nehru Sahkar Bhawan, 2nd Floor, Tonk Road, Jaipur - 302005",
    pincode: "302005",
    phone: "0141-2740112",
    email: "obc-corp-rj@rajasthan.gov.in",
    website: "https://sje.rajasthan.gov.in",
    categories: ["OBC"],
    handles: ["nbcfdc-general", "nbcfdc-swarnima", "nbcfdc-saksham", "nbcfdc-shilpsampada"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Linked with Jan Aadhaar portal for automated eligibility verification."
  },

  // BIHAR
  {
    id: "sca-br-scst",
    name: "Bihar State SC & ST Co-operative Development Corp. (BSSCDC)",
    type: "State Channelising Agency (SCA - SC/ST)",
    state: "Bihar",
    city: "Patna",
    address: "Social Welfare Complex, Bailey Road, Patna - 800001",
    pincode: "800001",
    phone: "0612-2223842",
    email: "md_scstcorp_bihar@yahoo.co.in",
    website: "https://scst.bihar.gov.in",
    categories: ["SC", "ST", "SafaiKaramchari"],
    handles: ["term", "micro", "msy", "may", "nstfdc-term", "nstfdc-amsy", "nskfdc-term", "nskfdc-suy"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Partnered with Bihar Mahila Vikas Nigam and Mukhyamantri Udyami Yojana."
  },
  {
    id: "sca-br-obc",
    name: "Bihar State Backward Classes Finance & Development Corporation",
    type: "State Channelising Agency (SCA - OBC / NBCFDC)",
    state: "Bihar",
    city: "Patna",
    address: "Ambedkar Bhavan, 3rd Floor, Harding Road, Patna - 800001",
    pincode: "800001",
    phone: "0612-2215284",
    email: "bcebchd-bih@nic.in",
    website: "https://state.bihar.gov.in/bcebc",
    categories: ["OBC"],
    handles: ["nbcfdc-general", "nbcfdc-swarnima", "nbcfdc-saksham", "nbcfdc-shilpsampada"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Channels NBCFDC loans across all 38 districts of Bihar."
  },

  // MADHYA PRADESH
  {
    id: "sca-mp-sc",
    name: "Madhya Pradesh State SC Development Corporation",
    type: "State Channelising Agency (SCA - SC/Safai Karamcharis)",
    state: "Madhya Pradesh",
    city: "Bhopal",
    address: "Rajiv Gandhi Bhawan, 35 Shyamla Hills, Bhopal - 462002",
    pincode: "462002",
    phone: "0755-2551465 / 0755-2551466",
    email: "mpsc_corp@mp.gov.in",
    website: "https://scdevelopmentmp.nic.in",
    categories: ["SC", "SafaiKaramchari"],
    handles: ["term", "micro", "msy", "may", "green", "nskfdc-term", "nskfdc-suy"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "District Antyavasayi Co-operative Societies coordinate regional disbursement."
  },
  {
    id: "sca-mp-st",
    name: "MP Tribal Co-operative Development Federation (Vanaushadhi / TRIFED MP)",
    type: "State Channelising Agency (SCA - ST / NSTFDC)",
    state: "Madhya Pradesh",
    city: "Bhopal",
    address: "35, Shyamla Hills, Bhopal - 462002",
    pincode: "462002",
    phone: "0755-2661548",
    email: "mptcdf@mp.gov.in",
    website: "https://tribal.mp.gov.in",
    categories: ["ST"],
    handles: ["nstfdc-term", "nstfdc-amsy", "nstfdc-micro", "nstfdc-forest", "pm-janman"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Operates specialized processing lines for minor forest produce and tribal micro-units."
  },
  {
    id: "sca-mp-obc",
    name: "Madhya Pradesh Backward Classes and Minorities Finance & Dev. Corp.",
    type: "State Channelising Agency (SCA - OBC / NBCFDC)",
    state: "Madhya Pradesh",
    city: "Bhopal",
    address: "Panchtatva Bhawan, 1st Floor, Link Road No. 2, Tulsi Nagar, Bhopal - 462003",
    pincode: "462003",
    phone: "0755-2552306",
    email: "mpbcmfdc@mp.gov.in",
    website: "https://bcwd.mp.gov.in",
    categories: ["OBC"],
    handles: ["nbcfdc-general", "nbcfdc-swarnima", "nbcfdc-saksham", "nbcfdc-shilpsampada"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Direct linkage with MP Samagra portal for streamlined DBT transfers."
  },

  // KERALA
  {
    id: "sca-kl-scst",
    name: "Kerala State Development Corp. for SC and ST Ltd. (KSDC)",
    type: "State Channelising Agency (SCA - SC/ST)",
    state: "Kerala",
    city: "Thrissur",
    address: "Town Hall Road, Thrissur - 680020",
    pincode: "680020",
    phone: "0487-2331074 / 0487-2331075",
    email: "ksdcscst@gmail.com",
    website: "https://ksdc-scst.kerala.gov.in",
    categories: ["SC", "ST", "SafaiKaramchari"],
    handles: ["term", "micro", "msy", "may", "green", "nstfdc-term", "nstfdc-amsy", "nskfdc-term", "nskfdc-suy"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Lowest default rate amongst SCAs; high uptake for green business & micro-enterprises."
  },
  {
    id: "sca-kl-obc",
    name: "Kerala State Backward Classes Development Corp. (KSBCDC)",
    type: "State Channelising Agency (SCA - OBC / NBCFDC)",
    state: "Kerala",
    city: "Thiruvananthapuram",
    address: "TC 27/588 (7) & (8), Sentinel, Pattoor, Vanchiyoor P.O., Thiruvananthapuram - 695035",
    pincode: "695035",
    phone: "0471-2577550 / 0471-2577539",
    email: "ksbcdc@gmail.com",
    website: "https://ksbcdc.com",
    categories: ["OBC"],
    handles: ["nbcfdc-general", "nbcfdc-swarnima", "nbcfdc-saksham", "nbcfdc-shilpsampada"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Leading state channelising agency in NBCFDC credit disbursement."
  },

  // ODISHA
  {
    id: "sca-od-scst",
    name: "Odisha SC and ST Dev. Finance Co-operative Corp. (OSFDC)",
    type: "State Channelising Agency (SCA - SC/ST)",
    state: "Odisha",
    city: "Bhubaneswar",
    address: "Lewis Road, Samantarapur, Bhubaneswar - 751002",
    pincode: "751002",
    phone: "0674-2430038 / 0674-2430039",
    email: "osfdc@nic.in",
    website: "https://osfdc.nic.in",
    categories: ["SC", "ST", "SafaiKaramchari"],
    handles: ["term", "micro", "msy", "may", "green", "nstfdc-term", "nstfdc-amsy", "nstfdc-forest", "pm-janman", "nskfdc-term", "nskfdc-suy"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Special focus on coastal artisans, tribal SHGs, and PVTG development."
  },

  // ANDHRA PRADESH
  {
    id: "sca-ap-scst",
    name: "AP Scheduled Castes Co-operative Finance Corp. Ltd. (APSCCFC)",
    type: "State Channelising Agency (SCA - SC)",
    state: "Andhra Pradesh",
    city: "Vijayawada",
    address: "D.No. 40-1-63, MG Road, Vijayawada - 520010",
    pincode: "520010",
    phone: "0866-2495577 / 0866-2495578",
    email: "md_apsccfc@yahoo.com",
    website: "https://apsccfc.ap.gov.in",
    categories: ["SC", "SafaiKaramchari"],
    handles: ["term", "micro", "msy", "may", "green", "nskfdc-term", "nskfdc-suy"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Synchronized with Navasakam village/ward secretariat delivery mechanism."
  },
  {
    id: "sca-ap-st",
    name: "Girijan Co-operative Corporation Ltd. (GCC)",
    type: "State Channelising Agency (SCA - ST / NSTFDC)",
    state: "Andhra Pradesh",
    city: "Visakhapatnam",
    address: "East Point Colony, Visakhapatnam - 530017",
    pincode: "530017",
    phone: "0891-2796428",
    email: "md_gcc@ap.gov.in",
    website: "https://girijan.ap.gov.in",
    categories: ["ST"],
    handles: ["nstfdc-term", "nstfdc-amsy", "nstfdc-micro", "nstfdc-forest", "pm-janman"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Pioneer in procurement, marketing and processing of minor forest produce for tribals."
  },

  // TELANGANA
  {
    id: "sca-ts-sc",
    name: "Telangana Scheduled Castes Co-operative Dev. Corp. (TSCCDC)",
    type: "State Channelising Agency (SCA - SC/Safai Karamcharis)",
    state: "Telangana",
    city: "Hyderabad",
    address: "Damodaram Sanjeevaiah Sankshema Bhavan, Masab Tank, Hyderabad - 500028",
    pincode: "500028",
    phone: "040-23395722 / 040-23395723",
    email: "vcmd_tsccdc@telangana.gov.in",
    website: "https://tsccdc.telangana.gov.in",
    categories: ["SC", "SafaiKaramchari"],
    handles: ["term", "micro", "msy", "may", "green", "nskfdc-term", "nskfdc-suy"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Co-ordinates state affirmative credit linkage and NSFDC channel financing."
  },
  {
    id: "sca-ts-st",
    name: "Telangana Tribal Co-operative Finance Dev. Corp. Ltd. (TRICOR)",
    type: "State Channelising Agency (SCA - ST / NSTFDC)",
    state: "Telangana",
    city: "Hyderabad",
    address: "DSS Bhavan, 1st Floor, Masab Tank, Hyderabad - 500028",
    pincode: "500028",
    phone: "040-23391782",
    email: "tricor.telangana@gmail.com",
    website: "https://tricor.telangana.gov.in",
    categories: ["ST"],
    handles: ["nstfdc-term", "nstfdc-amsy", "nstfdc-micro", "nstfdc-forest", "pm-janman"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Dedicated tribal corporation managing micro-enterprises and agro-processing in agency tracts."
  },

  // ASSAM & NORTH EAST
  {
    id: "sca-as-scst",
    name: "Assam State Development Corp. for Scheduled Castes Ltd.",
    type: "State Channelising Agency (SCA - SC)",
    state: "Assam",
    city: "Guwahati",
    address: "Ganeshguri, Chariali, Dispur, Guwahati - 781006",
    pincode: "781006",
    phone: "0361-2234055",
    email: "sc_assam@gov.in",
    website: "https://wptbc.assam.gov.in",
    categories: ["SC", "SafaiKaramchari"],
    handles: ["term", "micro", "msy", "may", "green", "nskfdc-term", "nskfdc-suy"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Handles channel finance across Brahmaputra and Barak valleys."
  },
  {
    id: "sca-as-st",
    name: "Assam Plains Tribes Development Corporation Ltd.",
    type: "State Channelising Agency (SCA - ST / NSTFDC)",
    state: "Assam",
    city: "Guwahati",
    address: "R.G. Baruah Road, Ganeshguri, Guwahati - 781005",
    pincode: "781005",
    phone: "0361-2452355",
    email: "aptdc@assam.gov.in",
    website: "https://wptbc.assam.gov.in",
    categories: ["ST"],
    handles: ["nstfdc-term", "nstfdc-amsy", "nstfdc-micro", "nstfdc-forest", "pm-janman"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Direct channelising agency for NSTFDC in Assam plains and tea garden tribal areas."
  },

  // PUNJAB & HARYANA
  {
    id: "sca-pb-sc",
    name: "Punjab Scheduled Castes Land Development & Finance Corp. (PSCFC)",
    type: "State Channelising Agency (SCA - SC/Safai Karamcharis)",
    state: "Punjab",
    city: "Chandigarh",
    address: "SCO 101-103, Sector 17-C, Chandigarh - 160017",
    pincode: "160017",
    phone: "0172-2702758 / 0172-2702759",
    email: "pscfc@punjab.gov.in",
    website: "https://pscfc.punjab.gov.in",
    categories: ["SC", "SafaiKaramchari"],
    handles: ["term", "micro", "msy", "may", "green", "nskfdc-term", "nskfdc-suy"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "High operational allocation for agro-allied, dairy, and sanitation machinery."
  },
  {
    id: "sca-hr-sc",
    name: "Haryana Scheduled Castes Finance & Development Corp. (HSCFDC)",
    type: "State Channelising Agency (SCA - SC/Safai Karamcharis)",
    state: "Haryana",
    city: "Chandigarh",
    address: "Bays No. 49-52, Sector 2, Panchkula - 134112",
    pincode: "134112",
    phone: "0172-2567083",
    email: "hscfdc@hry.nic.in",
    website: "https://hscfdc.gov.in",
    categories: ["SC", "SafaiKaramchari"],
    handles: ["term", "micro", "msy", "may", "green", "nskfdc-term", "nskfdc-suy"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Direct integration with Parivar Pehchan Patra (PPP) for automated verification."
  },

  // ==========================================
  // MSME DISTRICT INDUSTRIES CENTRES & KVIC STATE DIRECTORATES (General / EWS / All)
  // ==========================================
  {
    id: "dic-all-india",
    name: "District Industries Centre (DIC) / MSME Development & Facilitation Office",
    type: "District Industries Centre (MoMSME / State Dept)",
    state: "All India",
    city: "Present in every District Headquarters across 766+ Districts",
    address: "Office of the General Manager, District Industries Centre (DIC), Collectorate Compound",
    pincode: "Official District HQ",
    phone: "1800-180-6763 (MSME Champions Helpline)",
    email: "champions@gov.in",
    website: "https://champions.gov.in",
    categories: ["General", "EWS", "SC", "ST", "OBC", "SafaiKaramchari"],
    handles: ["pmegp-mfg", "pmegp-serv", "pmfme", "cgtmse", "sfurti", "nssh-subsidy", "aspire", "pm-vishwakarma", "coir-udyami", "tread"],
    maxFundingLimit: 50000000,
    isEligible: true,
    statusNote: "Primary sponsoring agency for PMEGP (35% subsidy), PMFME (35% subsidy) and PM Vishwakarma in all districts."
  },
  {
    id: "kvic-hq",
    name: "Khadi and Village Industries Commission (KVIC State Directorate)",
    type: "Central Nodal Agency (MoMSME)",
    state: "All India",
    city: "State Capitals & Zonal Divisions",
    address: "State Directorate of KVIC, Gramodaya Complex",
    pincode: "State Zonal HQ",
    phone: "1800-11-2005",
    email: "pmegp.kvic@gov.in",
    website: "https://kviconline.gov.in",
    categories: ["General", "EWS", "SC", "ST", "OBC", "SafaiKaramchari"],
    handles: ["pmegp-mfg", "pmegp-serv", "sfurti"],
    maxFundingLimit: 50000000,
    isEligible: true,
    statusNote: "Statutory clearing house for PMEGP credit-linked capital subsidy up to ₹50 Lakh."
  },

  // ==========================================
  // PUBLIC SECTOR COMMERCIAL BANKS (STAND-UP, MUDRA, AIF, KUSUM, CEGSSC)
  // ==========================================
  {
    id: "bank-sbi",
    name: "State Bank of India — SME & Financial Inclusion Branch",
    type: "Public Sector Commercial Bank (22,400+ Branches)",
    state: "All India",
    city: "Present in all Talukas, Mandals & Districts across India",
    address: "Local SBI Branch / Lead District Bank Office (Lead District Manager)",
    pincode: "Local Branch",
    phone: "1800-11-2211 / 1800-425-3800 (Toll Free)",
    email: "agm.sme@sbi.co.in",
    website: "https://sbi.co.in/web/business/sme",
    categories: ["General", "EWS", "SC", "ST", "OBC", "SafaiKaramchari"],
    handles: ["standup", "cegssc-cap", "mudra-shishu", "mudra-kishore", "mudra-tarun", "pm-vishwakarma", "aif", "pm-kusum", "pmmsy", "ahidf", "pmsvanidhi-1", "pmsvanidhi-2", "pmsvanidhi-3", "day-nrlm", "day-nulm-sep-i"],
    maxFundingLimit: 100000000,
    isEligible: true,
    statusNote: "Official Stand-Up India & MUDRA lead lender in over 450 districts; direct CEGSSC member."
  },
  {
    id: "bank-pnb",
    name: "Punjab National Bank — Priority Sector Lending Hub",
    type: "Public Sector Commercial Bank (10,000+ Branches)",
    state: "All India",
    city: "National Network across North, Central, East & West India",
    address: "Designated PNB MSME Care Branch / Lead District Office",
    pincode: "Local Branch",
    phone: "1800-180-2222 / 1800-103-2222",
    email: "sme@pnb.co.in",
    website: "https://pnbindia.in",
    categories: ["General", "EWS", "SC", "ST", "OBC", "SafaiKaramchari"],
    handles: ["standup", "cegssc-cap", "mudra-shishu", "mudra-kishore", "mudra-tarun", "pm-vishwakarma", "pmegp-mfg", "pmegp-serv", "pmsvanidhi-1", "pmsvanidhi-2", "pmsvanidhi-3"],
    maxFundingLimit: 100000000,
    isEligible: true,
    statusNote: "Key partner bank for Stand-Up India, MUDRA, and PMEGP in Northern & Central India."
  },
  {
    id: "bank-canara",
    name: "Canara Bank — MSME Sulabh & Priority Credit Hub",
    type: "Public Sector Commercial Bank (9,700+ Branches)",
    state: "All India",
    city: "National Network across Southern, Western & Eastern India",
    address: "Canara Bank Branch / Lead District Office",
    pincode: "Local Branch",
    phone: "1800-425-0018",
    email: "fid@canarabank.com",
    website: "https://canarabank.com",
    categories: ["General", "EWS", "SC", "ST", "OBC", "SafaiKaramchari"],
    handles: ["standup", "cegssc-cap", "mudra-shishu", "mudra-kishore", "mudra-tarun", "pm-vishwakarma", "day-nrlm", "aif", "pmmsy"],
    maxFundingLimit: 100000000,
    isEligible: true,
    statusNote: "Lead bank for Stand-Up India, SHG bank linkage (DAY-NRLM), and PMMSY fisheries credit."
  },
  {
    id: "bank-bob",
    name: "Bank of Baroda — Baroda MSME Baroda Yoddha Hub",
    type: "Public Sector Commercial Bank (8,200+ Branches)",
    state: "All India",
    city: "National Network across West, Central & South India",
    address: "Nearest Bank of Baroda SME / Retail Branch",
    pincode: "Local Branch",
    phone: "1800-5700 / 1800-258-4455",
    email: "msme.bcc@bankofbaroda.com",
    website: "https://bankofbaroda.in",
    categories: ["General", "EWS", "SC", "ST", "OBC", "SafaiKaramchari"],
    handles: ["standup", "cegssc-cap", "mudra-shishu", "mudra-kishore", "mudra-tarun", "pmegp-mfg", "pmegp-serv", "cgtmse"],
    maxFundingLimit: 100000000,
    isEligible: true,
    statusNote: "Recognized as leading lender under Stand-Up India and CEGSSC guarantees."
  }
];

if (typeof window !== "undefined") {
  window.REAL_PARTNERS = REAL_PARTNERS;
}
